### ISSUE TITLE
IAM Group Support

### ISSUE THREAD

**Issue by regicsolutions** [RoadieHQ/backstage-plugin-aws-auth#10]
## Feature Suggestion

In a environment with multiple VPC's it would be ideal to be able to authenticate using IAM Groups

**Comment by dtuite** [comment]
@regicsolutions We'd love to chat more about how you would like to see this working. Let us know how we can make that happen please.

**Comment by martina-if** [comment]
Hi @regicsolutions , this is not in our top priority right now and since there's not much activity here I will be closing this. If you still think this is important please feel free to reopen it. We also appreciate pull requests so if you have time for it we will be happy to review it!
